# Generated by Django 2.2 on 2022-08-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categ',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='categ',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
